[project]
name = "vlsi-grimoire"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "marimo>=0.17.0",
    "pyzmq>=27.1.0",
]
